error_narrator/__init__.py,sha256=2eEQMZqyxjKdBqoKO1WtTOynV2bDoEfWSD-C756zMBA,209
error_narrator/narrator.py,sha256=1FWqoWyRa-uufv0zFemZY2r8FQityzCVcr1xXTUK5IY,16334
error_narrator-0.2.1.dist-info/METADATA,sha256=1U1od0O6au6nhLR9cpsltgzkMNNnO4U-hiE9KsSriUI,3898
error_narrator-0.2.1.dist-info/WHEEL,sha256=b4K_helf-jlQoXBBETfwnf4B04YC67LOev0jo4fX5m8,88
error_narrator-0.2.1.dist-info/RECORD,,
